---
ocserv_base_dir: /var/ocserv
ocserv_config_dir: "{{ ocserv_base_dir }}/config"
ocserv_docker_image: "quay.io/telekomlabs/ocserv:1.2"
ocserv_timezone: "Asia/Tokyo"
ocserv_tcp_port: 443
ocserv_udp_port: 443
ocserv_service_domain: "snct-bastion.shiron.dev"
ocserv_device: "vpns"
ocserv_ipv4_network: "10.99.0.0"
ocserv_ipv4_netmask: "255.255.255.0"
ocserv_dns_servers:
  - 1.1.1.1
  - 8.8.8.8
ocserv_routes:
  - default
ocserv_no_routes: []
ocserv_max_clients: 32
ocserv_max_same_clients: 2
ocserv_keepalive: 32400
ocserv_dpd: 90
ocserv_mobile_dpd: 1800
ocserv_compression: true
ocserv_authorized_hosts: []
ocserv_tls_cert_src: "/etc/letsencrypt/live/{{ ocserv_service_domain }}/fullchain.pem"
ocserv_tls_key_src: "/etc/letsencrypt/live/{{ ocserv_service_domain }}/privkey.pem"
ocserv_compose_extra_volumes: []
ocserv_docker_env: {}
ocserv_users: []
