---
- name: Stop ocserv docker compose
  become: true
  ansible.builtin.command:
    cmd: docker compose down
    chdir: "{{ ocserv_base_dir }}"
  register: ocserv_compose_down
  failed_when: false
  changed_when: ocserv_compose_down.rc == 0
  listen: Restart ocserv docker compose

- name: Start ocserv docker compose
  become: true
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ ocserv_base_dir }}"
  register: ocserv_compose_up
  changed_when: ocserv_compose_up.rc == 0
  listen: Restart ocserv docker compose
