- name: Check if main/main.sops.yml exists
  ansible.builtin.stat:
    path: "{{ role_path }}/vars/main/main.sops.yml"
  register: main_sops_yml_stat
  delegate_to: localhost
  run_once: true
  failed_when: false

- name: Load encrypted variables from main/main.sops.yml
  ansible.builtin.include_vars:
    file: main/main.sops.yml
  when: main_sops_yml_stat.stat.exists | default(false)
  delegate_to: localhost
  run_once: true
  failed_when: false

- name: Check if main/main.yml exists
  ansible.builtin.stat:
    path: "{{ role_path }}/vars/main/main.yml"
  register: main_yml_stat
  delegate_to: localhost
  run_once: true
  failed_when: false

- name: Load variables from main/main.yml
  ansible.builtin.include_vars:
    file: main/main.yml
  when: main_yml_stat.stat.exists | default(false)
  delegate_to: localhost
  run_once: true
  failed_when: false

