- name: Deploy frp docker compose
  hosts: snct-proxy-srv.shiron.dev
  gather_facts: true
  roles:
    - role: frp
      tags:
        - frp
    - role: ocserv
      tags:
        - ocserv

- name: Deploy frp client
  hosts: edu-gpu-2
  gather_facts: true
  roles:
    - frpc
