- name: Setup kind cluster
  hosts: edu-gpu
  gather_facts: true
  roles:
    - role: kind
      tags:
        - kind
    - role: istio
      tags:
        - istio
    - role: argocd
      tags:
        - argocd
